### ISSUE TITLE
multiple rabbits crashes the app

### ISSUE THREAD

**Issue by JeanneColeongco** [ChloeColeongco/CoSpaces-Code#11]
figure out why (probably loops), fix or find alternative. see commented out code in document

**Comment by ChloeColeongco** [comment]
the app probably needed updating. using a VR compatible phone probably helps. see rabbit season for code.

**Comment by JeanneColeongco** [comment]
the app probably needed updating. using a VR compatible phone probably helps. see rabbit season for code.
